name: DoIt Test CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch/jerry branches
  push:
    branches:
      - jerry-*
      - main

jobs:
  playing-around:
    runs-on: ubuntu-20.04
    container:
      image: docker.io/jerrykrauss/doit-test:1
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - run: ls -la
      - run: doit list
      - run: doit help
      - run: doit help echo
      - run: doit echo --arg "hello world!"
      - run: doit hello_world
      - run: doit fibonacci
      - run: doit call_func
      - run: doit count
      - run: doit format && doit format
      - run: mkdir build && doit compile
      - run: doit modify
      - run: doit t*
      - run: doit x
      - run: doit title
      - run: doit package
      - run: doit fail
