name: DoIt Test CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch/jerry branches
  push:
    branches:
      - jerry-*
      - main

jobs:
  playing-around:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get install -y -q python3-doit=0.31.1-3.2ubuntu1 python3 clang
      - run: doit list
      - run: doit help
      - run: doit help echo
      - run: doit echo --arg "hello world!"
      - run: doit hello_world
      - run: doit fibonacci
      - run: doit call_func
      - run: doit count
      - run: doit format && doit format
      - run: doit compile
      - run: doit modify
      - run: doit t*
      - run: doit fail
      - run: doit x
      - run: doit title
      - run: doit package